# -*-encoding:utf-8-*-
from flask_babel import lazy_gettext
erks_portlets = {
    'board._posts': ('icon-bubbles', lazy_gettext(u'커뮤니티'), '', '', ''),
    'board._post_write': ('icon-bubbles', lazy_gettext(u'글쓰기'), '', '', ''),
    'board._post_modify': ('icon-bubbles', lazy_gettext(u'글수정'), '', '', ''),
    'board._post_replies_view': ('', lazy_gettext(u'답글보기'), '', '', ''),
    'board._notice_view': ('', lazy_gettext('공지사항보기'), '', 'light dialog', ''),
    'board._notice_write': ('', lazy_gettext('공지사항글작성'), '', 'light dialog', ''),
    'board._qna_view': ('', lazy_gettext('질문글보기'), '', 'light dialog', ''),
    'board._qna_write': ('', lazy_gettext('질문글작성'), '', 'light dialog', ''),
    'board._summary_projectgroup_notice': ('fa-volume-up', lazy_gettext(u'공지사항 | Notice'), '', '', ''),
    'board._summary_projectgroup_qna': ('fa-question-circle', lazy_gettext('질문 | Q&A'), '', '', ''),
    'board._project_group_notices': ('fa-volume-up', lazy_gettext(u'공지사항 | Notice'), '', '', ''),
    'board._project_group_qnas': ('fa-question-circle', lazy_gettext('질문 | Q&A'), '', '', ''),
    'glossary._glossary_view': ('icon-book-open', lazy_gettext(u'용어사전정보'), '', '', ''),
    'glossary._glossary_list': ('icon-book-open', lazy_gettext(u'용어사전목록'), '', '', ''),
    'glossary._glossary_new': ('icon-book-open', lazy_gettext(u'새로운 용어사전 만들기'), '', 'light form-fit', 'form'),
    'glossary._glossary_preference': ('icon-book-open', lazy_gettext(u'용어사전 환경설정'), '', 'light form-fit', 'form'),
    'glossary._glossary_preference_codeset': ('icon-book-open', lazy_gettext(u'용어사전내 선택항목 관리'), lazy_gettext(u'용어사전 관리에서 사용하는 코드성 데이타를 추가,수정,삭제할 수 있습니다.'), '', ''),
    'glossary._glossary_reports': ('icon-book-open', lazy_gettext(u'용어사전 리포트'), '', '', ''),
    'glossary_master._glossary_derived_codeterm': ('', lazy_gettext(u'코드용어 조회'), '', '', ''),
    'glossary_master._glossary_derived_codeterm_new': ('', lazy_gettext(u'코드용어 신규'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_codeterm_update': ('', lazy_gettext(u'코드용어 수정'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_codeterms': ('', lazy_gettext(u'코드용어 관리'), lazy_gettext(u'용어사전의 코드인스턴스를 관리합니다.'), '', ''),
    'glossary_master._glossary_derived_info': ('fa-exclamation-circle', lazy_gettext(u'용어사전정보'), lazy_gettext(u'전사용어집을 따르는 용어사전입니다.'), '', ''),
    'glossary_master._glossary_derived_model_reports': ('', lazy_gettext(u'모델별 용어사전 비교리포트'), lazy_gettext(u'이 용어사전과 연결된 모델의 리포트 정보입니다.'), '', ''),
    'glossary_master._glossary_derived_modify': ('', lazy_gettext(u'전사용어파생된 용어사전 환경설정'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_new': ('', lazy_gettext(u'파생용어사전 생성'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_nonstrdtermmap_new': ('', lazy_gettext(u'비표준용어맵핑 신규'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_nonstrdtermmap_update': ('', lazy_gettext(u'비표준용어맵핑 수정'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_nonstrdtermmaps': ('', lazy_gettext(u'비표준용어맵핑 관리'), lazy_gettext(u'비표준용어(표준용어에 속하지 않은 모델에서 사용되는 용어들)에 대하여 표준용어와의 맵핑정보를 관리합니다.'), '', ''),
    'glossary_master._glossary_derived_nonstrdterms': ('fa-circle', lazy_gettext(u'비표준용어목록'), lazy_gettext(u'프로젝트의 비표준용어를 조회합니다.'), '', ''),
    'glossary_master._glossary_derived_reports': ('', lazy_gettext(u'용어사전 정합성리포트'), lazy_gettext(u'용어사전 자체에 대한 리포트 정보입니다.'), '', ''),
    'glossary_master._glossary_derived_term_delete': ('', lazy_gettext(u'전사 표준용어 삭제 신청'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_term_master_view': ('', lazy_gettext(u'전사용어 조회'), '', '', 'form'),
    'glossary_master._glossary_derived_term_new': ('', lazy_gettext(u'신규 전사 표준용어 신청'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_term_request_view': ('', lazy_gettext(u'전사용어변경요청'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_term_requests': ('', lazy_gettext(u'용어요청목록(전사표준에 신청중인 내역입니다.)'), '', '', ''),
    'glossary_master._glossary_derived_term_update': ('', lazy_gettext(u'전사 표준용어 변경 신청'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_derived_terms': ('fa-exclamation-circle', lazy_gettext(u'용어목록정보'), lazy_gettext(u'전사표준용어를 조회합니다.'), '', ''),
    # 'glossary_master._glossary_master_codeterm': ('', lazy_gettext(u'전사코드용어'), '', '', ''),
    'glossary_master._glossary_master_codeterm_new': ('', lazy_gettext(u'전사코드용어 신규'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_codeterm_update': ('', lazy_gettext(u'전사코드용어 수정'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_codeterms': ('icon-layers', lazy_gettext(u'전사코드용어'), lazy_gettext(u'용어사전의 코드인스턴스를 관리합니다.'), '', ''),
    'glossary_master._glossary_master_info': ('icon-info-circle', lazy_gettext(u'전사 용어사전 정보'), '', '', ''),
    'glossary_master._glossary_master_infotype_new': ('', lazy_gettext(u'전사인포타입 등록'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_infotype_update': ('', lazy_gettext(u'인포타입 변경'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_infotypes': ('icon-layers', lazy_gettext(u'전사인포타입목록'), '', '', ''),
    'glossary_master._glossary_master_preference': ('', lazy_gettext(u'전사용어사전 환경설정'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_preference_codeset': ('', lazy_gettext(u'전사용어사전내 선택항목 관리'), lazy_gettext(u'용어사전 관리에서 사용하는 코드성 데이타를 추가,수정,삭제할 수 있습니다.'), '', ''),
    'glossary_master._glossary_master_reports': ('', lazy_gettext(u'전사용어사전 리포트'), '', '', ''),
    'glossary_master._glossary_master_term_new': ('', lazy_gettext(u'전사용어 등록'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_new_strdterm': ('', lazy_gettext(u'전사용어 등록'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_new_synonym': ('', lazy_gettext(u'전사금칙어 등록'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_new_unitterm': ('', lazy_gettext(u'전사단어 등록'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_request_review': ('icon-layers', lazy_gettext(u'전사용어 변경검토'), lazy_gettext(u'프로젝트 사용자의 전사용어 변경신청을 리뷰합니다. 승인/거절하거나 해당 프로젝트의 비표준으로 남겨둘 수 있습니다.'), 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_request_review_approve': ('', lazy_gettext(u'승인하기(수정/검토)'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_request_review_reject': ('', lazy_gettext(u'반려하기'), '', 'light form-fit dialog', 'form'),
    'glossary_master._glossary_master_term_requests': ('icon-layers', lazy_gettext(u'전사표준용어 변경신청'), '', '', ''),
    'glossary_master._glossary_master_term_update': ('', lazy_gettext(u'전사용어 변경'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_term_view': ('', lazy_gettext(u'전사용어 조회'), '', 'light form-fit', 'form'),
    'glossary_master._glossary_master_terms': ('icon-layers', lazy_gettext(u'전사표준용어'), '', '', ''),
    'glossary_master._glossary_master_xlsloaderhistorylist': ('icon-layers', lazy_gettext(u'XLS업로드 목록'), '', '', ''),
    'glossary_master._glossary_master_xlsloaderhistory': ('icon-layers', lazy_gettext(u'XLS업로드 처리결과상세'), '', '', ''),
    'infotype._glossary_infotype_new': ('fa-info-circle', lazy_gettext(u'인포타입추가'), lazy_gettext(u'인포타입 등록을 통해서 DBMS 별 데이터 타입을 관리할 수 있습니다.'), 'light form-fit', 'form'),
    'infotype._glossary_infotypes': ('fa-info-circle', lazy_gettext(u'인포타입목록'), '', '', ''),
    'infotype._modify_infotype': ('fa-info-circle', lazy_gettext(u'인포타입변경'), '', 'light form-fit', 'form'),
    'integrity._model_schema_report': ('fa-bar-chart', lazy_gettext(u'모델별 DB스키마 일치율'), '', '', ''),
    'login._change_password': ('fa-user', lazy_gettext(u'사용자 비밀번호 변경'), '', 'light form-fit', 'form'),
    'login._profile': ('fa-user', lazy_gettext(u'사용자 정보'), '', '', ''),
    'login._profile_edit': ('fa-user', lazy_gettext(u'사용자 정보 수정'), '', 'light form-fit', 'form'),
    'login._report_subscription': ('fa-bookmark-o', lazy_gettext(u'프로젝트 변경사항 이메일구독'), lazy_gettext(u'현재 구독중인 프로젝트목록입니다.'), '', ''),
    'project._invite': ('icon-users', lazy_gettext(u'프로젝트에 사용자 초대하기'), '', 'light form-fit dialog', 'form'),
    'project._invite_review': ('icon-users', lazy_gettext(u'프로젝트에 사용자 초대하기'), '', 'light form-fit dialog', 'form'),
    'project._members': ('icon-users', lazy_gettext(u'프로젝트 회원'), '', '', ''),
    'project._preference': ('icon-settings', lazy_gettext(u'프로젝트 설정'), '', 'light form-fit', 'form'),
    'project._subscription_log': ('icon-settings', lazy_gettext(u'구독 정보'), '', '', ''),
    'project._summary_board': ('icon-bubble', lazy_gettext(u'커뮤니티'), '', '', ''),
    'project._summary_glossary': ('icon-book-open', lazy_gettext(u'용어사전 개요'), '', '', ''),
    'project._summary_model': ('icon-layers', lazy_gettext(u'모델 개요'), '', '', ''),
    'project._subscribe': ('icon-book-open', lazy_gettext(u'프로젝트변경사항구독'), '', 'light form-fit dialog', 'form'),
    'project._preference_for_projectgroup': ('icon-book-open', lazy_gettext(u'프로젝트설정변경'), '', 'light form-fit dialog', 'form'),
    'project._subjectarea_recently_changed': ('fa-folder-open-o', lazy_gettext(u'최근 변경 주제영역'), '', '', ''),
    'project_group._info': ('fa-info-circle', lazy_gettext(u'프로젝트그룹 정보'), '', '', ''),
    'project_group._invite': ('icon-users', lazy_gettext(u'사용자 초대'), '', 'light form-fit dialog', 'form'),
    'project_group._pg_subscription_log': ('fa-diamond', lazy_gettext(u'프로젝트 구독 정보'), '', '', ''),
    'project_group._preference_basic': ('icon-settings', lazy_gettext(u'기본 설정'), lazy_gettext(u'프로젝트 그룹의 기본속성들을 변경할 수 있습니다.'), 'light form-fit', 'form'),
    'project_group._preference_glossaries': ('', lazy_gettext(u'전체 용어사전 목록'), '', '', ''),
    'project_group._preference_glossary_master': ('', lazy_gettext(u'전사 용어사전 설정'), '', 'light form-fit', 'form'),
    'project_group._preference_members': ('fa-user', lazy_gettext(u'사용자 초대/사용자 목록'), lazy_gettext(u'ER-C가입자에 한해서 초대 가능합니다.'), '', ''),
    'project_group._preference_members_autoinvite': ('', lazy_gettext(u'사용자 자동 등록 설정'), lazy_gettext(u'그룹에 사용자를 자동으로 등록할 수 있습니다.'), 'light form-fit', 'form'),
    'project_group._preference_project': ('', lazy_gettext(u'프로젝트 생성 설정'), '', 'light form-fit', 'form'),
    'project_group._preference_projects': ('', lazy_gettext(u'전체 프로젝트 목록'), '', '', ''),
    'project_group._preference_security': ('', lazy_gettext(u'보안설정'), '', 'light form-fit', 'form'),
    'project_group._user_role_changer': ('', lazy_gettext(u'프로젝트 그룹 사용자 권한 설정'), '', 'light form-fit dialog', 'form'),
    'projectuser._user_role_changer': ('', lazy_gettext(u'프로젝트 사용자 권한 설정'), '', 'light form-fit dialog', 'form'),
    'report._model_attributes': ('', lazy_gettext(u'속성 조회'), '', '', ''),
    'report._model_entities': ('', lazy_gettext(u'엔터티 조회'), '', '', ''),
    'report._model_glossary_report': ('fa-bar-chart', lazy_gettext(u'모델별 표준용어 일치율'), lazy_gettext(u'모델의 속성과 표준용어의 일치여부를 확인할 수 있습니다.'), '', ''),
    'report._model_report_info': ('fa-folder-open-o', lazy_gettext(u'모델 리포트'), '', '', ''),
    'report._model_scripts': ('', lazy_gettext(u'DB스크립트 생성'), '', '', ''),
    'report._model_validate_with_glossary': ('', lazy_gettext(u'표준점검'), '', '', ''),
    'schema._collectors': ('icon-layers', lazy_gettext(u'DB스키마 수집'), '', '', ''),
    'schema._model_modify_db_collector': ('icon-layers', lazy_gettext(u'DB수집 설정'), lazy_gettext(u'Database Schema 정보 수집에 대한 상세 설정을 추가/변경합니다.'), 'light form-fit', 'form'),
    'schema._model_schema_collect_result_dtl': ('icon-layers', lazy_gettext(u'Schema 수집결과상세조회'), '', '', ''),
    'schema._model_schema_collect_result_list': ('icon-layers', lazy_gettext(u'Schema 수집이력조회'), '', '', ''),
    'schema._model_schema_compare_dtl': ('icon-layers', lazy_gettext(u'모델-SCHEMA 비교'), lazy_gettext(u'데이터모델과 Database Schema 를 서로 비교한 결과를 조회합니다.'), '', ''),
    'schema._model_schema_collect_exceptions': ('icon-layers', lazy_gettext(u'DB수집기별 미사용테이블 등록'), '', 'light form-fit', 'form'),
    'term._glossary_terms': ('icon-layers', lazy_gettext(u'표준용어/표준단어/금칙어 목록'), '', '', ''),
    'term._term_regist': ('', lazy_gettext(u'용어 등록'), '', 'light form-fit', 'form'),
    'term._term_update': ('', lazy_gettext(u'용어 편집'), '', 'light form-fit', 'form'),
    'term._term_view': ('', lazy_gettext(u'용어 조회'), '', 'light form-fit', 'form'),
    'term._xlsloaderhistory': ('', lazy_gettext(u'XLS업로드 처리결과조회'), '', '', ''),
    'term._xlsloaderhistorylist': ('', lazy_gettext(u'XLS업로드 처리결과'), '', '', ''),
}
